// Ky skedar gjenerohet automatikisht nga "npm run generate"
// Mos e ndrysho manualisht.
export const lawList = [
  "1.Propozimi_i_gjithe_OSTve_per_nje_metodologji_te_ofrimit_te_dhenave_te_gjenerimit_dhe_ngarkeses_ne_perputhje_me_nenin.pdf",
  "162.1 rregullore mbi procedurat e konsultimit publik-finale.pdf",
  "2._Propozimi_i_gjithe_OSTve_mbi_operimin_e_sistemit_te_transmetimit_te_energj.pdf",
  "3._Dokument_shpjegues_i_propozimit_per_supozimet_dhe_metodologjine_per_nje_....pdf",
  "3._Hipotezat_dhe_Metodologjia_mbi_analizen_e_Kosto-Perfitim-it.pdf",
  "4._KORRR__me_amendimet__Clean.pdf",
  "80_a__RREGULLAT_OPERACIONALE_PER_FMF_GAZ_NATYROR-1.pdf",
  "AKSESI_NE_HAPESIRAT_E_DEPOZITIMIT_TE_GAZIT_NATYROR-_PROCEDURE_E_FILLUAR_ME_VENDIMIN_NR_8_DATE_19.01.2017-2.pdf",
  "Cmimet fmf 2020 ( publikime)25012021.pdf",
  "Cmimet_e_fmf-se_2019_perditesuar13_01_2020.pdf",
  "DPM_Kontrata_TIP-1.pdf",
  "DPM_Kontrata_TIP.pdf",
  "Draft-Metodologjia_e_FMF_Gaz(17062021) (1).pdf",
  "Draft-Metodologjia_e_FMF_Gaz(17062021).pdf",
  "final_-_rregullorja_per_kushtet_e_sherbimit_fmf_-_per_QPZ (1).pdf",
  "final_-_rregullorja_per_kushtet_e_sherbimit_fmf_-_per_QPZ.pdf",
  "Formati_TIP_i_licenses_se_Furnizimit-1.pdf",
  "Formati_TIP_i_licenses_se_Furnizimit.pdf",
  "KESHILLI_MINISTRAVE_NR.1804_V2022.pdf",
  "KESH_FSHU_V_Nr_95_Dt_20052024_Kontrata_si_pjese_e_ketij_vendimi.pdf",
  "KESH_FTL_NR.1847-3_V2024-3-10.pdf",
  "KM_VKM_NR.398_DT_9.6.22_PER_TRAJTIM_DISBALANCA_398.pdf",
  "Kodi Civil.pdf",
  "Kodi Doganor.pdf",
  "Kodi Penal.pdf",
  "Kodi Procedures Administrative.pdf",
  "Kodi Procedures Civilie.pdf",
  "Kodi Punes.pdf",
  "Kodi Rrugor.pdf",
  "Kodi_i_etikes_ere.pdf",
  "Kodi_i_Matjes_Vendim_nr.101,_date_26.8.2008.pdf",
  "Kodi_i_Rrjetit_per_HDVC_2018-04-PHLG.pdf",
  "Kodi_i_Rrjetit_per_lidhjen_e_Gjeneruesve_2018-03-PHLG.pdf",
  "Kodi_i_rrjetit_per_Lidhjen_e_Ngarkeses_2018-05-PHLG (1).pdf",
  "Kodi_i_rrjetit_per_Lidhjen_e_Ngarkeses_2018-05-PHLG.pdf",
  "Kodi_i_Rrjetit_qe_harmonizon_strukturat_tarifore_te_transmetimit_te_gazit(1).pdf",
  "Kodi_i_rrjetit_TAP.pdf",
  "Kodi_i_Rrjetit_te_Transmetimit_te_GN_28.04.2020.pdf",
  "KODI_I_TRANSMETIMIT-1.pdf",
  "Kodi_i_Transmetimit_Vendim_nr._63_2022.pdf",
  "Kodi_Shperndarjes_Vendimi_nr.100,_date_26.8.2008.pdf",
  "Kontrata_TIP_KESH-FSHU_sh.a_e_ndryshuar_v21.pdf",
  "Kontrata_universal_final_28_3_18.pdf",
  "KONTRATE_OSHEE-PPE_ripare_me_vendimin_147_30_09_2016_(002)-1 (1).pdf",
  "KONTRATE_OSHEE-PPE_ripare_me_vendimin_147_30_09_2016_(002)-1.pdf",
  "Kontrate_per_ofrimin_e_sherbimeve_te_Zyrtarit_te_Perputhshmerise_vendim_78_dt_26.05.2017-2.pdf",
  "Kriteret_per_te_vendosur_derogime_per_modulet_gjeneruese_te_energjise_elektrike.pdf",
  "Kushtet_mbi_vendosjen_e_detyrimit_te_sherbimit_universal.pdf",
  "Licenca TIP per veprimtarine operimit ne hapesirat e depozitimit te gazit natyror -web (1).pdf",
  "Licenca TIP per veprimtarine operimit ne hapesirat e depozitimit te gazit natyror -web.pdf",
  "Licenca_e_furnizimit_te_gazit_natyor (1).pdf",
  "Licenca_e_furnizimit_te_gazit_natyor.pdf",
  "LICENCA_E_SHPERNDARJES_SE_GAZIT_NATYROR_FIN-1.pdf",
  "LICENCA_E_SHPERNDARJES_SE_GAZIT_NATYROR_FIN.pdf",
  "licenca_e_shperndarje_formatuar-1.pdf",
  "licenca_e_shperndarje_formatuar_finale.pdf",
  "LICENCA_E_TRANSMETIMIT_GAZ_FIN (1).pdf",
  "LICENCA_E_TRANSMETIMIT_GAZ_FIN.pdf",
  "licenca_e_tregetimit_te_gazit_natyror (1).pdf",
  "licenca_e_tregetimit_te_gazit_natyror.pdf",
  "Licenca_tip_per_veprimtarine_operimit_ne_Impiantet_GNL (1).pdf",
  "Licenca_tip_per_veprimtarine_operimit_ne_Impiantet_GNL.pdf",
  "LICENSA_E_OPERATORIT_TE_TREGUT_TE_ENERGJISE_ELEKTRIKE-_miratuar_me_V_123_dt_21.07.2016 (1).pdf",
  "LICENSA_E_OPERATORIT_TE_TREGUT_TE_ENERGJISE_ELEKTRIKE-_miratuar_me_V_123_dt_21.07.2016.pdf",
  "LICENSA_E_PRODHIMIT_TE_ENERGJISE_ELEKTRIKE_MIRATUAR_ME_VENDIMIN_NR.99,_DATE_17.06..pdf",
  "LICENSA_E_PRODHIMIT_TE_ENERGJISE_ELEKTRIKE_MIRATUAR_ME_VENDIMIN_NR.99,_DATE_17.06.2016.pdf",
  "LICENSA_E_TREGTIMIT_TE_EN-_EL_MIRATUAR_ME_VENDIMIN_97,_DATE_17.06.2019.pdf",
  "LICENSA_E_TREGTIMIT_TE_ENERGJISE_ELEKTRIKE_MIRATUAR_ME_VENDIMIN_97,_DATE_17.06.2019.pdf",
  "license_per_operimin_e_sistemit_te_transmetimit_te_en-el_.pdf",
  "license_per_operimin_e_sistemit_te_transmetimit_te_en-el_1.pdf",
  "Lidhje 141- RREGULLORE PER PERCAKTIMIN E KRITEREVE TE VLERESIMIT DHE TE PERZGJEDHJES  FMF.pdf",
  "lidhje 166 Kushtet e kontrates tip te furnizimit e korigjuar -per botim.pdf",
  "lidhje 217 PLANI I MASAVE i rishikuar.pdf",
  "lidhje 266 -KODI I MATJES PER MIRATIM-- reflektimet.pdf",
  "lidhje 273 Rregullore_Burimet_Dytesore 23.12. 2020_REV.docxfinal.pdf",
  "Lidhje vendim 129 rreg pagesat.pdf",
  "lidhje_23_RREGULLORE_MBI_MASAT_E_TË_TË_LICENSUARVE_NË_AKTIVITETIN_E_FURNIZIMIT_PËR_ARRITJEN_E_TREGUESVe_ndryshimet_25.01.2022_FINAL.pdf",
  "Ligj_43_2015 PËR SEKTORIN E ENERGJISË ELEKTRIKE.pdf",
  "Ligj_nr._102_dt._23.9.2015_Për_sektorin_e_gazit_natyror__ndryshuar.pdf",
  "ligj_nr._24_2023 PËR NXITJEN E PËRDORIMIT TË ENERGJISË NGA BURIMET RINOVUESHME.pdf",
  "LISTA_E_LLOGARIVE_DHE_UDHEZIMI_PERKATES.pdf",
  "Lista_e_llogarive_per_qellime_te_rregullimit_per_furnizuesin_publik.pdf",
  "Lista_e_llogarive_per_qellime_te_rregullimit_per_kompanine_e_Shperndarjes.pdf",
  "Lista_e_llogarive_per_qellime_te_rregullimit_per_kompanine_e_Transmetimit.pdf",
  "Lista_e_tarifave_ALPEX.pdf",
  "Manuali_i_Pergjithshem_i_Llogarive.pdf",
  "MARREDHENIET_KONTRAKTUALE_TE_FURNIZIMIT.pdf",
  "Marreveshja_e_Lidhjes_se_Re_ne_Sistemin_e_Transmetimit.pdf",
  "Marreveshja_e_sherbimit_te_transmetimit_te_en-el_ndermjet_OST_sh.a._dhe_Furnizuesit_te_en-el.pdf",
  "Marreveshja_Operimit.pdf",
  "marreveshja_per__pjesmarrjen_ne_treg.pdf",
  "Metodologjia_CGMM.pdf",
  "Metodologjia_CID.pdf",
  "Metodologjia_e_amenduar_VENDIM_233 (1).pdf",
  "Metodologjia_e_amenduar_VENDIM_233.pdf",
  "METODOLOGJIA_E_CMIMIT_TE_TRANSMETIMIT_DHE_SHPERNDARJES_SE_GAZIT_VENDIMI_178__DATE_08.11.2017(1).pdf",
  "METODOLOGJIA_E_CMIMIT_TE_TRANSMETIMIT_DHE_SHPERNDARJES_SE_GAZIT_VENDIMI_178__DATE_08.11.20171.pdf",
  "Metodologjia_e_demit_ekonomik._E_azhornuar.pdf",
  "Metodologjia_e_llogaritjes_se_detyrimit_te_energjise_se_rinovueshme.pdf",
  "METODOLOGJIA_E_LLOGARITJES_SE_TARIFAVE_TE_OPERATORIT_TE_SHOQERISE_SE_PRODHIMIT_TE_ENERGJISE_ELEKTRIKE.pdf",
  "METODOLOGJIA_E_LLOGARITJES_SE_TARIFAVE_TE_OPERATORIT_TE_SISTEMIT_TE_SHPERNDARJES_SE_ENERGJISE_ELEKTRIKE-1 (1).pdf",
  "METODOLOGJIA_E_LLOGARITJES_SE_TARIFAVE_TE_OPERATORIT_TE_SISTEMIT_TE_SHPERNDARJES_SE_ENERGJISE_ELEKTRIKE-1.pdf",
  "Metodologjia_e_llogaritjes_se_tarifave_te_transmetimit_te_energjise_elektrike-2 (1).pdf",
  "Metodologjia_e_llogaritjes_se_tarifave_te_transmetimit_te_energjise_elektrike-2.pdf",
  "Metodologjia_e_llogaritjes_se_tarifes_Rigazifikimi_GNL__Miratim_01122021_10122021 (1).pdf",
  "Metodologjia_e_llogaritjes_se_tarifes_Rigazifikimi_GNL__Miratim_01122021_10122021.pdf",
  "Metodologjia_FSHU-1.pdf",
  "Metodologjia_FSHU.pdf",
  "Metodologjia_per_koordinimin_e_analizes_se_sigurise_operative._finalja.pdf",
  "Metodologji_llogaritja_e_tarifës_për_shërbimin_e_sistemit_të_depozitimit_të_gazit_natyror.pdf",
  "miratimi_i_marreveshjes_se_sherbimit_te_shperndarjes_se_en-el_ndermjet_oshe-furnizuesit_te_en-el__-1.pdf",
  "Miratimi_i_transpozimit_te_Rregullores.pdf",
  "Miratim_i_Programit_te_Perputhshmeris_-2.pdf",
  "Perkufizimet_e_Rregullave_te_tregut_te_energjise_elektrike.pdf",
  "Procedura_e_Klerimit_dhe_Shlyerjes.pdf",
  "Procedura_e_Tregtimit.pdf",
  "Programi_i_Pajtueshmerise_miratim_i_formatuar_(1).pdf",
  "Propozimi_i_te_gjitha_OST-ve_per_kerkesat_shtese_te_FCR_al_v2.pdf",
  "regjistri_i_kualifikimieve_02.11.2009.pdf",
  "Regullorja_per_Ndryshimin_e_Furnizuesit_te_Energjise_elektrike_.pdf",
  "Rregullat e Tregut Shqiptar te Balancimit te Energjise Elektrike.pdf",
  "Rregullat operacionale per furnizuesin e ngarkuar me detyrimin e sherbimit publik per sektorin e gazit natyror.pdf",
  "RREGULLAT PER MONITORIMIN E TREGUT TE GAZIT NATYROR- miratim-clean.pdf",
  "RREGULLAT_E_BLERJES_SE_ENERGJISE_PER_MBULIMIN_E_HUMBJEVE_NE_SHPERNDARJE_DHE_TRANSMETIM_V.103,_DT.23.06.2016.pdf",
  "RREGULLAT_E_MENAXHIMIT_TE_KAPACITETIT_TE_KUFIZUAR-_miratuar_me_V_124_dt_21.07.2016.pdf",
  "Rregullat_e_Tregut_Shqiptare_te_Energjise_Elektrike_-1.pdf",
  "Rregullat_e_Tregut_Shqiptar_te_Balancimit_te_Energjise_Elektrike.pdf",
  "Rregullat_e_Tregut_te_Energjise_Elektrike_-Termat_e_Pergjithshme.pdf",
  "RREGULLAT_MBI_KUSHTET_E_PERGJITHSHME_TE_SHERBIMIT_TE_FURNIZIMIT_ME_GAZ_NATYROR__PER_KLIENTET_FUNDOR.pdf",
  "Rregullat_per_Certifikimin_e_Operatorit_te_Sistemit_te_Transmetimit_per_Gazin_Natyror.pdf",
  "Rregullat_per_licensimin_ne_sektorin_e_gazit_natyror(1) (1).pdf",
  "Rregullat_per_licensimin_ne_sektorin_e_gazit_natyror(1).pdf",
  "Rregullat_per_monitorimin_e_tregut_te_energjise (1).pdf",
  "Rregullat_per_monitorimin_e_tregut_te_energjise.pdf",
  "RREGULLAT_PER_PUBLIKIMIN_E_TE_DHENAVE_BAZE_TE_TREGUT_TE_en-el.pdf",
  "Rregullat_per_publikimin_e_te_dhenave_te_tregut_te_energjise_elektrike.pdf",
  "Rregullat__per_percaktimin_e_formatit_te_te_dhenave_dhe_proceduren_per_aksesin_e_Furnizuesve_ndaj_te_dhenave_te_OSHEE-1.pdf",
  "RREGULLORE PËR ORGANIZIMIN, FUNKSIONIMIN DHE PROÇEDURAT E ERE-s.pdf",
  "RREGULLORE_E_PROCEDURAVE_PER_LIDHJET_E_REJA_DHE_MODIFIKIMIN_E_LIDHJEVE_EKZISTUESE_NE_SISTEMIN_E_TRANSMETIMIT-2.pdf",
  "rregullore_e__certifikimit_te_ost_energjise_elektrike-1.pdf",
  "Rregullore_per_cilesine_e_furnizimit_dhe_performancen_e_sigurise_se_rrjetit_ne_sistemin_e_transmetimit_te_energjise_elektrike_OST11012022.pdf",
  "RREGULLORE_PER_KRITERET_STANDARTE_TE_CILESISE_SE_SHERBIMIT_TE_FURNIZIMIT_DHE_PERFORMANCES_SE_SIGURISE_SE_RRJETIT_TE_SHPERNARJES_SE_ENERGJISE_ELEKTRIKE_treguesit16062021.pdf",
  "Rregullore_per_leshimin_tranferimin_dhe_anullimin_e_garancive_te_origjines_per_Energjine_Elektrike_te_prodhura_nga_burimet_e_rinovueshme.pdf",
  "Rregullore_per_Lidhjet_e_reja_2024.pdf",
  "rregullore_per_mbrojtjen_e_info_konfidencial (1).pdf",
  "rregullore_per_mbrojtjen_e_info_konfidencial.pdf",
  "Rregullore_per_ndryshimin_e_furnizuesit_ne_sektorin_e_gazit_natyror.pdf",
  "RREGULLORE_PER_PARAQITJEN_E_PLANIT_TE_INVESTIMEVE_GAZ_NATYROR.pdf",
  "Rregullore_per_percaktimin_klasifikimin_e_Sistemeve_te_Mbyllura_te_Shperndarjes_se_energjise-1.pdf",
  "rregullore_per_procedurat_e_paraqitjes_dhe_miratimit_te_planit_te_investimeve_nga_operatoret_e_transmetimit_dhe_shperndarjes_se_en-el-1.pdf",
  "Rregullore_per_procedura_dhe_afatet_per_dhenien_e_autorizimit_nga_ERE_per_ndryshimin_pdf (1).pdf",
  "Rregullore_per_procedura_dhe_afatet_per_dhenien_e_autorizimit_nga_ERE_per_ndryshimin_pdf.pdf",
  "RREGULLORE_PER_SIGURIMIN_E_AKSESIT_TE_PALEVE_TE_TRETA_NE_SISTEMIN_E_TRANSMETIMIT_DHE_TRANSPARENCEN_NE_SEKTORIN_E_GAZIT_NATYROR_5_04_2018.pdf",
  "RREGULLORE_PËR_PROCEDURAT_DHE_AFATET_PËR_DHËNIEN_MODIFIKIMIN_TRANSFERIMIN_RINOVIMIN_NJOHJEN_DHE_HEQJEN_E_LICENCAVE_NË_SEKTORIN_E_ENERGJISË_ELEKTRIKE_002 (1).pdf",
  "RREGULLORE_PËR_PROCEDURAT_DHE_AFATET_PËR_DHËNIEN_MODIFIKIMIN_TRANSFERIMIN_RINOVIMIN_NJOHJEN_DHE_HEQJEN_E_LICENCAVE_NË_SEKTORIN_E_ENERGJISË_ELEKTRIKE_002.pdf",
  "Rregullore_Remit_Finale_21102021.pdf",
  "RREGULLORE_TRANSFERIM_ASETESH-_miratuar_119_21.07.2016.pdf",
  "RREGULLORE_TRANSFERIM_ASETESHmiratuar_119_21.07.2016 (1).pdf",
  "RREGULLORE_TRANSFERIM_ASETESHmiratuar_119_21.07.2016.pdf",
  "Rregullorja mbi procedurat per dhenien e te drejtes se perjashtimit per infrastrukturen e re te gazit natyror.pdf",
  "Rregullorja organizimit ERE 1  12 - finale.pdf",
  "Rregullorja_e_alokimit_Shadow.pdf",
  "Rregullorja_e_Alokimit_te_Kapaciteteve_2018-1.pdf",
  "Rregullorja_e_Ankandit_per_Alokimin_e_Kapaciteteve_SEE_CAO (1).pdf",
  "Rregullorja_e_Ankandit_per_Alokimin_e_Kapaciteteve_SEE_CAO.pdf",
  "RREGULLORJA_E_BLERJES_SE_ENERGJISE_NDRYSHUAR_ME_VENDIMIN_NR._168,_DATE_23.06.2016-1.pdf",
  "RREGULLORJA_E_FUNKSIONIMIT_TE_ERE_MIRATUAR_ME_VENDIMIN_NR__96_DATE_17_06.pdf",
  "RREGULLORJA_E_HEQJES_SE_LICENCAVE_ENERGJI_DHE_GAZ_PROCEDURE_E_FILLUAR_ME_VENDIMIN_NR_6_DATE_19.01.2017-2.pdf",
  "Rregullorja_e_lidhjeve_te_reja_Gazi_Natyror_f.pdf",
  "Rregullorja_e_Perdorimit_te_Terminalit_te_GNL.pdf",
  "Rregullorja_e_Sigurise_Kibernetike.pdf",
  "rregullorja_e__Heqjes_se_licencave (1).pdf",
  "rregullorja_e__Heqjes_se_licencave.pdf",
  "Rregullorja_mbi_kushtet_e_pergjitheshme__te_sherbimit_te_furnizmit_me_Energji_Elektrike_per_klientet_fundor_ (1).pdf",
  "Rregullorja_mbi_kushtet_e_pergjitheshme__te_sherbimit_te_furnizmit_me_Energji_Elektrike_per_klientet_fundor_.pdf",
  "RREGULLORJA_MBI_PROCEDURAT_PER_PARAQITJEN_E_NJE_KERKESE_SHQYRTIMIN_E_SAJ_DHE_AFATET_E_NJOFTIMIT_KUR_KLIENTI_DYSHON_NE_SAKTESINE_E_TE_DHENAVE_TE_APARATIT_MATES_TE_ENERGJISE_ELEKTRIKE-2.pdf",
  "Rregullorja_mbi_Sistemin_e_Njesuar_te_Llogarive_per_Shoqerite_e_Rregulluara_ne_Sektorin_e_Gazit_Natyror.pdf",
  "Rregullorja_mbi_Sistemin_e_Njësuar_të_Llogarive_për_Shoqëritë_e_Rregulluara_në_Sektorin_e_Gazit_Natyror.pdf",
  "rregullorja_nemo.pdf",
  "Rregullorja_per_kriteret_e__nderprerjes_te_Klienteve_ne_Nevoje_per_QPZ_-_final.pdf",
  "Rregullorja_per_zgjidhjen_e_mosmarreveshjeve.pdf",
  "RREGULLROJA_E_GJOBAVE_FINALE_MIRATUAR_ME_VENDIMIN_125,_DT.29.07.2016.pdf",
  "RREG_E_GJOBAVE_NE_SEKTORIN_E_GAZIT_NATYROR.pdf",
  "RREG__PER_CILESINE_E__GAZIT__DATE_21_06_2019_(e_paster).pdf",
  "SEE_CAO_AL_copy.pdf",
  "SHKURTIME_DHE_TERMINOLOGJI.pdf",
  "Shpjegime_per_Karakteristikat_Shtese_te_Rezervave_te_Mbajtjes_se_Frekuences_al_V2.pdf",
  "Shtojca_1_Formati_i_aplikimit.pdf",
  "Shtojca_2_te_dhenat_teknike_per_prodhimin.pdf",
  "Shtojca_3_te_dhena_teknike_per_transmetimin_e_energjise_elektrike.pdf",
  "Shtojca_4_Te_dhenat_teknike_per_shperndarjen.pdf",
  "Shtojca_III_Rregullorja_e_Perdorimit_te_Terminalit_te_GNL.pdf",
  "sistemi_informacionit_qe_i_licensuari_duhet_te_paraqesi_ne_ere_3.pdf",
  "Standartet_e_trajtimit_te_kerkesave_te_klienteve_lidhje_Vendim_nr_60_dt_25.2.21_003.pdf",
  "Tabela_e_Publikimit_të_Çmimit_FMF16012023.pdf",
  "Tabela_e_Çmimeve_FMF_për_vitin_2025.pdf",
  "TABELA_E_ÇMIMIT_TË_SHITJES_SË_ENERGJISË_NGA_FMF_1_pdf.pdf",
  "TABELA_PËRDITËSUAR_E_TARIFAVE_DHE_ÇMIMEVE_2024_.pdf",
  "Tabela_për_publikim_çmimet_për_FMF-202116022022.pdf",
  "Tarifat 2021 shqip.pdf",
  "Tarifate_e_miratuara_nga_ERE.pdf",
  "Tarifate_e_miratuara_nga_ERE_1janar-31_mars2017.pdf",
  "Tarifate_e_miratuara_nga_ERE_Prill_-_Dhjetor2017.pdf",
  "Tarifat_dhe_cmimet_2022.pdf",
  "Tarifat_dhe_cmimet_202222122022.pdf",
  "Tarifat_dhe_cmimet_202227102022.pdf",
  "Tarifat_dhe_cmimet_2022_18022022.pdf",
  "Tarifat_dhe_cmimet_2023.pdf",
  "Tarifat_dhe_Cmimet_ne _fuqi_per_vitin_2020.pdf",
  "Tarifat_dhe_Çmimet_e_Energjisë_Elektrike_dhe_Gazit_Natyror_për_periudhën_1_janar_-31_janar_2025.pdf",
  "Tarifat_dhe_Çmimet_e_energjisë_Elektrike_dhe_Gazit_natyror_për_periudhën_1_Shkurt-31_Dhjetor_2025.pdf",
  "tarifat_e_miratuara_nga_ERE_per_vitin_2019.pdf",
  "Treguesit e Matjes per Cilesine e Furnizimit dhe Performances te OST 2021.pdf",
  "Treguesit per kriteret standarde te cilesise se sherbimit te furnizimit dhe performances se sigurise se rrjetit te shperndarjes se en-el per vitin 2021.pdf",
  "Udherrefyesi_2023.pdf",
  "Udhezues_per_Menaxhimin_dhe_Alokimin_e_Kapaciteteve_ne_Projektin_TAP_24.05.2012.pdf",
  "vendim-2021-10-08-584.pdf",
  "vendim-2022-04-29-256.pdf",
  "vendim-2022-06-29-456 (1).pdf",
  "vendim-2022-06-29-456.pdf",
  "vendim-2022-12-27-872_2.pdf",
  "vendim-2025-02-26-118 (1).pdf",
  "vendim-2025-02-26-118.pdf",
  "Vendimet_per_cmimet_2018-FMF.pdf",
  "Vendimi_Nr_347_2022_rregullat_e_tregut.pdf",
  "VENDIM_NR.112_2020_Profilet_e_Standartizuara_te_Ngarkeses.pdf",
  "VENDIM_Nr._337_datë_5.6.2024.pdf",
  "VKM-nr.-590-dat-9.10.2018.pdf",
  "VKM_nr.519-2016_Per_miratimin_e_Modelit_te_Tregut_te_Energjise_Elektrike_e_ndryshuar.pdf",
  "Çmimi_i_shitjes_së_energjisë_elektrike_nga_Furnizuesi_i_Mundësisë_së_Fundit.pdf"
];
